name: yoyaku
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.1
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  dio: ^4.0.6
  file_picker: ^4.5.1
  connectivity_plus: ^2.3.0
  intl: ^0.17.0
  uuid: ^3.0.6
  fluttertoast: ^8.0.9
  table_calendar: ^3.0.5
  xml: ^5.3.1
  url_launcher: ^6.1.0
  flutter_speed_dial: ^5.1.0
  http: ^0.13.4
  google_sign_in: ^5.3.0
  flutter_phoenix: ^1.0.0
  permission_handler: ^9.2.0
  csv: ^5.0.1
  file_saver: ^0.1.0
  flutter_archive: ^4.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  drift_dev: ^1.5.2
  build_runner: ^2.1.8

flutter:
  uses-material-design: true

  assets:
    - assets/
